# Generated by Django 3.2.7 on 2021-11-07 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_CLIENTE', models.CharField(max_length=250)),
                ('CPF_CNPJ_CLIENTE', models.CharField(max_length=50)),
                ('endereco_1_CLIENTE', models.CharField(max_length=250)),
                ('endereco_2_CLIENTE', models.CharField(blank=True, max_length=250, null=True)),
                ('contato_telefone_comercial_CLIENTE', models.CharField(max_length=10)),
                ('contato_telefone_residencial_CLIENTE', models.CharField(blank=True, max_length=10, null=True)),
                ('contato_email_CLIENTE', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao_CLIENTE', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_PRODUTO', models.CharField(max_length=1000)),
                ('nome_PRODUTO', models.CharField(max_length=1000)),
                ('descricao_PRODUTO', models.CharField(blank=True, max_length=1000, null=True)),
                ('codigo_PRODUTO', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email_USUARIO', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('nome_USUARIO', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CAD_Klee.clientes')),
                ('produtos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CAD_Klee.produtos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
