# Generated by Django 3.2.7 on 2021-11-08 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Último login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_PRODUTO', models.TextField()),
                ('nome_PRODUTO', models.TextField()),
                ('descricao_PRODUTO', models.TextField(blank=True, null=True)),
                ('codigo_PRODUTO', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_CLIENTE', models.TextField()),
                ('CPF_CNPJ_CLIENTE', models.TextField()),
                ('endereco_1_CLIENTE', models.TextField()),
                ('endereco_2_CLIENTE', models.TextField(blank=True, null=True)),
                ('contato_telefone_comercial_CLIENTE', models.TextField()),
                ('contato_telefone_residencial_CLIENTE', models.TextField(blank=True, null=True)),
                ('contato_email_CLIENTE', models.TextField(blank=True, null=True)),
                ('descricao_CLIENTE', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
