# Generated by Django 3.2.7 on 2021-11-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAD_Klee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clientes',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='produtos',
        ),
    ]
