# Generated by Django 3.2.7 on 2021-11-07 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAD_Klee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email_USUARIO',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nome_USUARIO',
            new_name='username',
        ),
    ]
