# Generated by Django 3.2.7 on 2021-11-08 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAD_Klee', '0002_auto_20211107_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clientes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CAD_Klee.clientes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='produtos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CAD_Klee.produtos'),
        ),
    ]
