# Generated by Django 3.2.7 on 2021-11-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD_Klee', '0003_auto_20211107_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clientes',
        ),
        migrations.AddField(
            model_name='usuario',
            name='clientes',
            field=models.ManyToManyField(blank=True, null=True, to='CAD_Klee.Clientes'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='produtos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, to='CAD_Klee.Produtos'),
        ),
    ]
