# Generated by Django 3.2.7 on 2021-11-08 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAD_Klee', '0004_auto_20211107_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clientes',
        ),
        migrations.AddField(
            model_name='usuario',
            name='clientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CAD_Klee.clientes'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='produtos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='produtos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CAD_Klee.produtos'),
        ),
    ]
