# Generated by Django 3.2.7 on 2021-11-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAD_Klee', '0004_auto_20211108_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='usuario',
            new_name='user',
        ),
    ]
