# Generated by Django 3.2.7 on 2021-11-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAD_Klee', '0005_auto_20211108_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='CAD_Klee.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='CAD_Klee.usuario'),
            preserve_default=False,
        ),
    ]
