# Generated by Django 3.2.7 on 2021-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD_Klee', '0007_auto_20211108_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade_PRODUTO',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
